### ISSUE TITLE
Allow user to choose PREFIX

### ISSUE THREAD

**Issue by GrpeApple** [shpkg/shpkg#3]
Instead of *automatically* using `sudo`. By default; install to their dedicated directory and configure PATH. [Just like `brew` does](https://github.com/Homebrew/brew/blob/master/docs/Installation.md#alternative-installs). Users can disable this and install to the dedicated directory.

**Comment by GrpeApple** [comment]
Thus, you can symbolic link to `${HOME}/.shpkg/usr/bin`.

**Comment by WMCB-Tech** [comment]
`shpkg` build scripts do not require `sudo` permissions unless the build script attempts to install files in `/usr`, and probably depends on a build script

some build script do not require sudo, you can take [Flat Remix GTK Theme](https://github.com/shpkg/ports/blob/e2e63f3f6bf880f2d998d5ea1cff9aa61d4c3325/flat-remix-gtk-theme/SHPKG_BUILD#L13) as an example and installs files in user's home directory

***

There may be a logic that it is indeed to be implemented, like an optional `PREFIX_DIR` environment variable, although build scripts ain't that hardcoded and can be tinkered by the user

**Comment by GrpeApple** [comment]
I see
