### ISSUE TITLE
shpkg repo not work

### ISSUE THREAD

**Issue by Yisus7u7** [shpkg/shpkg#7]
![Screenshot_20210731-145124](https://user-images.githubusercontent.com/64093255/127751015-2ad7f736-1bfc-4e18-af5a-b9dc3d82c398.png)

I Create a repository to test shpkg and when you put `shpkg update` It doesn't work

https://github.com/Yisus7u7/shpkg-builds.git

**Comment by WMCB-Tech** [comment]
did you read:
https://github.com/shpkg/shpkg/blob/master/docs/repo.md#known-bugs-in-the-repolist-file

make sure no comment or newlines are in `repolists` file as it isn't fixed yet. you may wish to restart, cleanup everything and try agaib

**Comment by Yisus7u7** [comment]
When I delete the default repository, and leave only my own, it works smoothly

**Comment by Yisus7u7** [comment]
Apparently that must already be a bug

**Comment by GrpeApple** [comment]
This issue would be great for referencing by pull requests, though I do not have the time to implement.

**Comment by WMCB-Tech** [comment]
I reproduced your problem and happens to me as well

![Screenshot_2021-08-01-12-56-06-99_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/65075766/127759741-de388893-7ab1-4bd8-806a-d4ecb12f272c.jpg)

tmpdir just needs to clear out

**Comment by Yisus7u7** [comment]
Okey, I'll wait for an update to fix it

**Comment by GrpeApple** [comment]
#10

**Comment by WMCB-Tech** [comment]
only pending fix is tmpdir clearing, although just need to append `rm` commands
